name: bizlogika_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+3

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  table_calendar: ^3.1.3
  intl: ^0.19.0
  http: ^1.2.2
  fluttertoast: ^8.2.10
  local_auth: ^2.3.0
  shared_preferences: ^2.3.4
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  # flutter_local_notifications: ^16.0.0
  awesome_notifications: ^0.10.0
  googleapis_auth: ^1.6.0
  path_provider: ^2.1.5
  open_file: ^3.5.10
  # pdf: ^3.11.2
  material_dialogs: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
    - assets/icons/dashboard_icons/
    - assets/icons/settings_icons/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

